const cartProductIns = {
  PS_TABELA_CARRINHO: [
    {
      PS_ID_CARRINHO: '12218',
      PS_FEEDBACK: 'As informa\u00e7\u00f5es carregadas com sucesso',
      PS_ID_ERRO: '0',
      PS_SESSAO: 'c2fcde6b184dfc25ff28f8a5cf4b1da8',
      PS_ID_CLIENTE: '0',
      PS_ID_VENDEDOR: '',
      PS_ID_PG_FORMA: '13',
      PS_PG_FORMA: 'PAGSEGURO/BOLETO',
      PS_TIPO_FRETE: 'CORREIO PAC',
      PS_ID_TIPO_FRETE: '41068',
      PS_VL_FRETE: '0',
      PS_PRAZO_ENTREGA_DIA: '',
      PS_CEP: '0',
      PS_VL_PARCELA: '',
      PS_VL_TOTAL_PARCELADO: '',
      PS_VL_DESCONTO: '0',
      PS_TX_DESCONTO_CODP: '',
      PS_CODIGOP: '',
      PS_QUANTIDADESDEITENS: '1',
      PS_VL_SUBTOTAL: '21',
      PS_VL_TOTAL_GERAL: '21',
      PS_VL_DELIVERY: '10',
      PS_DATADOCADASTRO: '09/02/2018 21:46:32',
      PS_ANOTACOES: '',
    },
  ],
  PS_TABELA_ITENS: [
    {
      PS_REGISTROS_COUNT: '1',
      PS_ID_MOVIMENTO_CAR: '22426',
      PS_ID_CARRINHO: '12218',
      PS_ID_PRODUTO: '25775',
      PS_DESCRICAO: 'Graxa de Silicone 50g IMPLASTEC',
      PS_QT: '1',
      PS_VL_UNITARIO: '21',
      PS_ID_IMAGEM: '168058',
      PS_PATH_IMAGEM_60: 'http://dominio.com/a.jpg',
      PS_PATH_IMAGEM_ZOMM: 'http://dominio.com/b.jpg',
      PS_IMAGEM_TXT_ALT: 'Graxa de Silicone 50g IMPLASTEC',
      PS_IMAGEM_TXT_TITLE: 'Graxa de Silicone 50g IMPLASTEC',
      PS_PATH_PAGE: '',
      PS_LINK_TITLE: 'Acesse maiores informa\u00e7\u00f5es  Graxa de Silicone 50g IMPLASTEC',
      PS_PESO: '0',
      PS_ALTURA_MM: '0',
      PS_COMPRIMENTO_MM: '0',
      PS_DIAMETRO_MM: '0',
      PS_LARGURA_MM: '0',
      PS_FORMATO_ENVIO: 'Indefindo',
      PS_VALOR_TOTAL: '21',
      PS_VALOR_DE_VENDA: '21',
      PS_ESTOQUE_LOJA: '11',
      PS_ESTOQUE_FILIA: '10',
      PS_ESTOQUE_DEPOSITO: '0',
      PS_ESTOQUE_TOTAL: '21',
      PS_DATADOCADASTRO: '09/02/2018 21:46:32',
    },
  ],
  PS_ID_ERRO: 0,
  PS_ALERTA: 7,
  PS_FEEDBACK: 'Produto adicionado ao carrinho com sucesso',
}


const cartSel = {
  result: [
    {
      PS_TABELA_CARRINHO: [
        {
          PS_ID_CARRINHO: '12218',
          PS_FEEDBACK: 'As informa\u00e7\u00f5es carregadas com sucesso',
          PS_ID_ERRO: '0',
          PS_SESSAO: 'c2fcde6b184dfc25ff28f8a5cf4b1da8',
          PS_ID_CLIENTE: '0',
          PS_ID_VENDEDOR: '',
          PS_ID_PG_FORMA: '13',
          PS_PG_FORMA: 'PAGSEGURO/BOLETO',
          PS_TIPO_FRETE: 'CORREIO PAC',
          PS_ID_TIPO_FRETE: '41068',
          PS_VL_FRETE: '0',
          PS_PRAZO_ENTREGA_DIA: '',
          PS_CEP: '0',
          PS_VL_PARCELA: '',
          PS_VL_TOTAL_PARCELADO: '',
          PS_VL_DESCONTO: '0',
          PS_TX_DESCONTO_CODP: '',
          PS_CODIGOP: '',
          PS_QUANTIDADESDEITENS: '1',
          PS_VL_SUBTOTAL: '21',
          PS_VL_TOTAL_GERAL: '21',
          PS_VL_DELIVERY: '10',
          PS_DATADOCADASTRO: '09/02/2018 21:46:32',
          PS_ANOTACOES: '',
        },
      ],
      PS_TABELA_ITENS: [
        {
          PS_REGISTROS_COUNT: '1',
          PS_ID_MOVIMENTO_CAR: '22426',
          PS_ID_CARRINHO: '12218',
          PS_ID_PRODUTO: '25775',
          PS_DESCRICAO: 'Graxa de Silicone 50g IMPLASTEC',
          PS_QT: '1',
          PS_VL_UNITARIO: '21',
          PS_ID_IMAGEM: '168058',
          PS_PATH_IMAGEM_60: 'http://dominio.com/a.jpg',
          PS_PATH_IMAGEM_ZOMM: 'http://dominio.com/b.jpg',
          PS_IMAGEM_TXT_ALT: 'Graxa de Silicone 50g IMPLASTEC',
          PS_IMAGEM_TXT_TITLE: 'Graxa de Silicone 50g IMPLASTEC',
          PS_PATH_PAGE: '',
          PS_LINK_TITLE: 'Acesse maiores informa\u00e7\u00f5es  Graxa de Silicone 50g IMPLASTEC',
          PS_PESO: '0',
          PS_ALTURA_MM: '0',
          PS_COMPRIMENTO_MM: '0',
          PS_DIAMETRO_MM: '0',
          PS_LARGURA_MM: '0',
          PS_FORMATO_ENVIO: 'Indefindo',
          PS_VALOR_TOTAL: '21',
          PS_VALOR_DE_VENDA: '21',
          PS_ESTOQUE_LOJA: '11',
          PS_ESTOQUE_FILIA: '10',
          PS_ESTOQUE_DEPOSITO: '0',
          PS_ESTOQUE_TOTAL: '21',
          PS_DATADOCADASTRO: '09/02/2018 21:46:32',
        },
      ],
      PS_ID_ERRO: 0,
      PS_ALERTA: 7,
      PS_FEEDBACK: '\u00cdtens do carrinho carregados com sucesso',
    },
  ],
}

const cartProductQuant = {
  result: [
    {
      PS_TABELA_CARRINHO: [
        {
          PS_ID_CARRINHO: '12218',
          PS_FEEDBACK: 'As informa\u00e7\u00f5es carregadas com sucesso',
          PS_ID_ERRO: '0',
          PS_SESSAO: 'c2fcde6b184dfc25ff28f8a5cf4b1da8',
          PS_ID_CLIENTE: '0',
          PS_ID_VENDEDOR: '',
          PS_ID_PG_FORMA: '13',
          PS_PG_FORMA: 'PAGSEGURO/BOLETO',
          PS_TIPO_FRETE: 'CORREIO PAC',
          PS_ID_TIPO_FRETE: '41068',
          PS_VL_FRETE: '0',
          PS_PRAZO_ENTREGA_DIA: '',
          PS_CEP: '0',
          PS_VL_PARCELA: '',
          PS_VL_TOTAL_PARCELADO: '',
          PS_VL_DESCONTO: '0',
          PS_TX_DESCONTO_CODP: '',
          PS_CODIGOP: '',
          PS_QUANTIDADESDEITENS: '1',
          PS_VL_SUBTOTAL: '42',
          PS_VL_TOTAL_GERAL: '42',
          PS_VL_DELIVERY: '10',
          PS_DATADOCADASTRO: '09/02/2018 21:46:32',
          PS_ANOTACOES: '',
        },
      ],
      PS_TABELA_ITENS: [
        {
          PS_REGISTROS_COUNT: '1',
          PS_ID_MOVIMENTO_CAR: '22426',
          PS_ID_CARRINHO: '12218',
          PS_ID_PRODUTO: '25775',
          PS_DESCRICAO: 'Graxa de Silicone 50g IMPLASTEC',
          PS_QT: '2',
          PS_VL_UNITARIO: '21',
          PS_ID_IMAGEM: '168058',
          PS_PATH_IMAGEM_60: 'http://dominio.com/a.jpg',
          PS_PATH_IMAGEM_ZOMM: 'http://dominio.com/b.jpg',
          PS_IMAGEM_TXT_ALT: 'Graxa de Silicone 50g IMPLASTEC',
          PS_IMAGEM_TXT_TITLE: 'Graxa de Silicone 50g IMPLASTEC',
          PS_PATH_PAGE: '',
          PS_LINK_TITLE: 'Acesse maiores informa\u00e7\u00f5es  Graxa de Silicone 50g IMPLASTEC',
          PS_PESO: '0',
          PS_ALTURA_MM: '0',
          PS_COMPRIMENTO_MM: '0',
          PS_DIAMETRO_MM: '0',
          PS_LARGURA_MM: '0',
          PS_FORMATO_ENVIO: 'Indefindo',
          PS_VALOR_TOTAL: '42',
          PS_VALOR_DE_VENDA: '21',
          PS_ESTOQUE_LOJA: '11',
          PS_ESTOQUE_FILIA: '10',
          PS_ESTOQUE_DEPOSITO: '0',
          PS_ESTOQUE_TOTAL: '21',
          PS_DATADOCADASTRO: '09/02/2018 21:46:32',
        },
      ],
      PS_ID_ERRO: 0,
      PS_ALERTA: 7,
      PS_FEEDBACK: 'As informa\u00e7\u00f5es carregadas com sucesso',
    },
  ],
}

const cartProductDelete = {
  PS_TABELA_CARRINHO: [
    {
      PS_ID_CARRINHO: '12218',
      PS_FEEDBACK: 'As informa\u00e7\u00f5es carregadas com sucesso',
      PS_ID_ERRO: '0',
      PS_SESSAO: 'c2fcde6b184dfc25ff28f8a5cf4b1da8',
      PS_ID_CLIENTE: '0',
      PS_ID_VENDEDOR: '',
      PS_ID_PG_FORMA: '13',
      PS_PG_FORMA: 'PAGSEGURO/BOLETO',
      PS_TIPO_FRETE: 'CORREIO PAC',
      PS_ID_TIPO_FRETE: '41068',
      PS_VL_FRETE: '0',
      PS_PRAZO_ENTREGA_DIA: '',
      PS_CEP: '0',
      PS_VL_PARCELA: '',
      PS_VL_TOTAL_PARCELADO: '',
      PS_VL_DESCONTO: '0',
      PS_TX_DESCONTO_CODP: '',
      PS_CODIGOP: '',
      PS_QUANTIDADESDEITENS: '0',
      PS_VL_SUBTOTAL: '0',
      PS_VL_TOTAL_GERAL: '0',
      PS_VL_DELIVERY: '10',
      PS_DATADOCADASTRO: '09/02/2018 21:46:32',
      PS_ANOTACOES: '',
    },
  ],
  PS_TABELA_ITENS: [],
  PS_ID_ERRO: 0,
  PS_ALERTA: 7,
  PS_FEEDBACK: 'As informa\u00e7\u00f5es carregadas com sucesso',
}

const cartProdutDeleteError = {
  PS_ID_ERRO: 2,
  PS_ALERTA: 206,
  PS_FEEDBACK: 'O cadastro com a id: 22426 não existe para ser excluido',
}

export default {
  cartProductIns,
  cartSel,
  cartProductQuant,
  cartProductDelete,
  cartProdutDeleteError,
}
