const get = {
  result: [
    {
      PS_TABELA_INFO: [
        {
          PS_ID_PESSOA: '9493',
          PS_NOME: 'Csthost WEB Builder',
          PS_ID_TIPO: '2',
          PS_ID_IMAGEM: '52381',
          PS_PATH_PAGE: '2013/4/52381/52385/gilvancosta.jpg',
          PS_FONE_PRINCIPAL: '8436633255',
          PS_FONE_MOVEL: '0',
          PS_FONE_FIXO: '0',
          PS_TIPO_DE_PESSOA: 'PESSOA JUR\u00cdDICA',
          PS_STATUS: 'APROVADO',
          PS_ID_TBL_PRODUTO_TAXA: '1',
          PS_ID_STATUS_CLIENTE: '50',
          PS_ID_STATUS_REVENDA: '45',
          PS_ID_VENDEDOR: '0',
          PS_FLAG_EMAIL_MKT: '1',
          PS_FLAG_ENDERECO: '0',
          PS_ANOTACOES: '',
          PS_PRIMEIRO_NOME: 'CSTHost',
          PS_NOME_DO_MEIO: 'Web',
          PS_SOBRENOME: 'Builder',
          PS_GENERO: 'M',
          PS_TRATAMENTO: 'sr',
          PS_CPF: '12312312315',
          PS_RG: '123',
          PS_TRABALHANAEMPRESA: 'CSTHOST WEB BILDER',
          PS_CARGO: 'GERENTE T\u00c9CNICO',
          PS_FORMACAOACADEMICA: '',
          PS_DATADONASCIMENTO: '',
          PS_RAZAO_SOCIAL: '',
          PS_NOME_FANTASIA: 'dsda',
          PS_CNPJ: '',
          PS_DATA_CNPJ: '',
          PS_INSC_ESTADUAL: '6766',
          PS_INSC_MUNICIPAL: '5454',
          PS_NOME_RESPONSAVEL: '',
          PS_CARGO_RESPONSAVEL: '',
          PS_ATIVIDADE_PRINCIPAL: '',
          PS_MISSAO_VISAO: '',
          PS_CEP: '59132020',
          PS_ENDERECO: 'Rua dos Jesu\u00edtas (Conj. Vila Verde I)',
          PS_ENDERECO_NUMERO: '117',
          PS_COMPLEMENTO: '',
          PS_BAIRRO: 'Paju\u00e7ara',
          PS_CIDADE: 'Natal',
          PS_UF: 'RN',
          PS_REGIAO_PAIS: '',
          PS_PAIS: '',
          PS_CEP_ENTREGA: '59132020',
          PS_ENDERECO_ENTREGA: '',
          PS_ENDERECO_NUMERO_ENTREGA: '',
          PS_COMPLEMENTO_ENTREGA: '',
          PS_BAIRRO_ENTREGA: '',
          PS_CIDADE_ENTREGA: '',
          PS_UF_ENTREGA: '',
          PS_REGIAO_ENTREGA: '',
          PS_PAIS_ENTREGA: '',
          PS_WEBSITES: '',
          PS_SKYPE: '',
          PS_FACEBOOK: '',
          PS_TWITTER: '',
          PS_GOOGLEPLUS: '',
          PS_LINKEDIN: '',
          PS_EMAIL_DE_LOGIN: 'gilvancosta2010@gmail.com',
          PS_ID_LINKEDIN: '',
          PS_ID_TWITTER: '',
          PS_ID_GOOGLE: '',
          PS_ID_FACEBOOK: '',
          PS_ACESSOWEB: '1',
          PS_NIVEL: '0',
        },
      ],
      PS_ALERTA: 7,
      PS_FEEDBACK: ' Resultados:1 cliente em  (188 milisegundos) ',
    },
  ],
}

const getResult = {
  acadamic_formation: '',
  accessweb: '1',
  address: 'Rua dos Jesuítas (Conj. Vila Verde I)',
  address_city: 'Natal',
  address_complement: '',
  address_country: '',
  address_neighborhood: 'Pajuçara',
  address_number: '117',
  address_region: '',
  address_state: 'RN',
  bussness: 'CSTHOST WEB BILDER',
  cep: '59132020',
  client_status_id: '50',
  cnpj: '',
  cpf: '12312312315',
  date_birth: '',
  date_cnpj: '',
  delivery_address: '59132020',
  delivery_address_city: '',
  delivery_address_complement: '',
  delivery_address_country: '',
  delivery_address_name: '',
  delivery_address_neighborhood: '',
  delivery_address_number: '',
  delivery_address_region: '',
  delivery_address_state: '',
  email: 'gilvancosta2010@gmail.com',
  facebook: '',
  facebook_id: '',
  fantasy_name: 'dsda',
  first_name: 'CSTHost',
  flag_address: '0',
  flag_email_mkt: '1',
  gender: 'M',
  google_id: '',
  googleplus: '',
  image_id: '52381',
  insc_municipal: '5454',
  insc_state: '6766',
  landline: '0',
  last_name: 'Builder',
  level: '0',
  linkedin: '',
  linkedin_id: '',
  main_office: '',
  middle_name: 'Web',
  name: 'Csthost WEB Builder',
  name_responsible: '',
  notes: '',
  office: 'GERENTE TÉCNICO',
  office_responsible: '',
  path_page: '2013/4/52381/52385/gilvancosta.jpg',
  phone_main: '8436633255',
  phone_mobile: '0',
  resale_status_id: '45',
  rg: '123',
  seller_id: '0',
  skype: '',
  social_name: '',
  status: 'APROVADO',
  tbl_product_taxt_id: '1',
  treatment: 'sr',
  twitter: '',
  twitter_id: '',
  type_id: '2',
  user_id: '9493',
  user_type: 'PESSOA JURÍDICA',
  vision_mission: '',
  website: '',
}

const getDontFind = {
  result: [
    {
      PS_TABELA_INFO: [
        {
          PS_FEEDBACK: 'Não encontrado',
        },
      ],
      PS_ALERTA: 206,
      PS_FEEDBACK: 'Não encontrado',
    },
  ],
}

const getDontFindResult = {
  PS_TABELA_INFO: [
    {
      PS_FEEDBACK: 'Não encontrado',
    },
  ],
  PS_ALERTA: 206,
  PS_FEEDBACK: 'Não encontrado',
}

const getDontFindResetPassword = {
  PS_ALERTA: 206,
  PS_FEEDBACK: 'Informa\u00e7\u00e3o do usu\u00e1rio inv\u00e1lida',
}

const getResetPassword = {
  PS_ID_PESSOA: 6738,
  PS_NOME: 'JANAINA',
}

const checkHash = {
  PS_ID_PESSOA: 9529,
  PS_NOME: 'David Santana (testecompra)',
}

const checkHashFall = {
  PS_ALERTA: 206,
  PS_FEEDBACK: 'Chave inv\u00e1lida',
}

export default {
  get,
  getResult,
  getResetPassword,
  getDontFind,
  getDontFindResult,
  getDontFindResetPassword,
  checkHash,
  checkHashFall,
}
