/* eslint max-len: "off" */

export const offer = {
  RegularPriceDolar: 13.27,
  familyName: 'Sports & Entretenimento',
  flagDestiny: 0,
  flagUnavaliable: 0,
  flatNotBrazil: 0,
  freeShipping: 0,
  groupName: 'Pesca',
  idMerchant: 0,
  idOffer: 904925,
  idProductMain: 241126,
  idProject: 44,
  metaDescription: 'Ofertas do mundo inteiro Iscas de Pesca Aproveite as Ofertas para venda quente agradável caixa de 40 pcs durable prático moscas artificiais iscas com ganchos de pesca pena',
  metaFocusKeyword: 'Iscas de Pesca',
  metaTitle: 'Iscas de Pesca Caixa de 40 Iscas com Ganchos de Pesca Venda Quente Agradável',
  name: 'Caixa de 40 Iscas com Ganchos de Pesca Venda Quente Agradável Pcs Durable Prático Moscas Artificiais Pena',
  noindex: 0,
  offerSalesLetter: '',
  project: 'PESCA',
  refOffer: 'A904925E',
  refProduct: '32858874542',
  regularPriceReal: 48.95,
  salePriceDolar: 12.21,
  salePriceReal: 45.05,
  slug: 'iscas-de-pesca-caixa-de-40-iscas-com-ganchos-de-pesca-venda-quente-agradavel-pcs-durable',
  subGroupName1: 'Iscas de Pesca',
  subGroupName2: '',
  subGroupName3: '',
  urlAffiliate: 'http://s.click.aliexpress.com/deep_link.htm?dl_target_url=https%3A%2F%2Fpt.aliexpress.com%2Fitem%2FHot-Selling-Nice-Box-40Pcs-Durable-pesca-Feather-Practical-Artificial-Flies-Lures-With-Hooks%2F32858874542.html&aff_short_key=7iaYFMN',
  urlDestiny: 'https://pt.aliexpress.com/item/Hot-Selling-Nice-Box-40Pcs-Durable-pesca-Feather-Practical-Artificial-Flies-Lures-With-Hooks/32858874542.html',
  urlImage: 'https://ae01.alicdn.com/kf/HTB1.VSvOXXXXXbKapXXq6xXFXXXu/venda-quente-agradavel-caixa-de-40-pcs-durable-pratico-moscas-artificiais-iscas-com-ganchos-de-pesca.jpg',
}

export const offers = [offer]
