export const CATEGORIES_FULL = 'CATEGORIES_FULL'
export const SET_FAMILY_ID = 'SET_FAMILY_ID'
export const SET_SESSION = 'SET_SESSION'
export const SET_CART = 'SET_CART'
export const SET_CART_ITENS = 'SET_CART_ITENS'
